name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to Remote Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/my-turborepo
            git pull origin main
            source ~/.nvm/nvm.sh
            nvm use
            pnpm install
            pnpm turbo run build
            pm2 restart all
          EOF
